env:
  global:
    - CC_TEST_REPORTER_ID=7d94d67fc5648b074222dd15e493baab59faba901b4f3558f3ff967ab3c832af

language: python

python:
  - "3.6"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - py.test --cov=flashlight test/dummy_test.py

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
