env:
  global:
    - CC_TEST_REPORTER_ID=7d94d67fc5648b074222dd15e493baab59faba901b4f3558f3ff967ab3c832af

language: python

python:
  - "3.5"
  - "3.6"

install:
  - travis_retry pip install -r requirements.txt
  - if [ $TRAVIS_PYTHON_VERSION = "3.5" ]; then travis_retry pip install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp35-cp35m-linux_x86_64.whl; fi
  - if [ $TRAVIS_PYTHON_VERSION = "3.6" ]; then travis_retry pip install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp36-cp36m-linux_x86_64.whl; fi
  - travis_retry python setup.py install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - py.test --cov=flashlight --cov-report xml tests

after_script:
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
