env:
  global:
    - CC_TEST_REPORTER_ID=7d94d67fc5648b074222dd15e493baab59faba901b4f3558f3ff967ab3c832af

language: python

python:
  - "3.5"
  - "3.6"

install:
  - travis_retry pip install -r requirements.txt
  - wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1ZGd3luqwQ0rNHvFvuSosM9BPsG3cCPgB' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1ZGd3luqwQ0rNHvFvuSosM9BPsG3cCPgB" -O torch-0.4.0a0_8056399-cp34-cp34m-linux_x86_64.whl && rm -rf /tmp/cookies.txt
  - travis_retry python -m wheel install torch-0.4.0a0_8056399-cp34-cp34m-linux_x86_64.whl
  - travis_retry python setup.py build develop

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - py.test --cov=flashlight --cov-report xml test

after_script:
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
