language: python
python:
  - "3.6"
before_install:
  - pip install git+https://github.com/pytorch/pytorch#egg=pytorch
  - pip install git+https://github.com/dlguys/flashlight#egg=flashlight
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test